### ISSUE TITLE
ResultDescription

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#433]
Should resultDescription in [Result](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#result-0) reference a URI or a [ResultDescription](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#resultdescription) class?

**Comment by amiller-ims** [comment]
The Achievement class defines the possible results: https://github.com/IMSGlobal/openbadges-specification/blob/a4633b2351fcdec9664ebd8eb26d984afbc8be5a/ob_v3p0/common_credentials.lines#L20

And the Result references the resultDescription being asserted: https://github.com/IMSGlobal/openbadges-specification/blob/a4633b2351fcdec9664ebd8eb26d984afbc8be5a/ob_v3p0/common_credentials.lines#L133

For example, https://github.com/IMSGlobal/openbadges-specification/blob/a4633b2351fcdec9664ebd8eb26d984afbc8be5a/ob_v3p0/examples/fullOpenBadge.html#L449-L468

**Comment by ottonomy** [comment]
Because the `ResultDescription` entity is expected to appear elsewhere in the same document, the original plan for the use of the `resultDescription` property within the `Result` class was to be an identifier to identify *which* `ResultDescription` was being referenced, rather than a full duplication of that ResultDescription.
