### ISSUE TITLE
Issuer Type Question

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#470]
According to the schema, issuer.type must be an array. Is this correct? What other type would the issuer be in addition to the profile at the same time?

**Comment by mgylling** [comment]
Cf. #471. Same question basically.

**Comment by martyr280** [comment]
@kayaelle @mgylling discuss at 10/20 workgroup?

**Comment by ottonomy** [comment]
I think the intent was:
* Some implementers at times would want to express an additional type outside of those specified by OB/CLR for core objects like an Achievement or a Profile. This allows for market-based exploration of additional capabilities.
* For data type consistency, whenever a value that could have one or multiple values is presented, an Array is used so that consumer systems more easily can process the data, and we as a spec-drafting community can more simply express the desired data types.

**Comment by xaviaracil** [comment]
Solved in working group meeting on 10/22: Add compaction support for arrays .
