### ISSUE TITLE
Choose a DID method

### ISSUE THREAD

**Issue by Sakurann** [1EdTech/openbadges-specification#489]
The text currently says: "This specification allows the use of an HTTP URL (e.g. https://1edtech.org/keys/1) or a DID URL (e.g. did:key:123), but only requires HTTP URL support."

DID support is optional, but if different implementations choose different DID methods, there will be no interoperability.

**Comment by nklomp** [comment]
Yeah mentioned this in the VC-ED/JFF plugfest the other day as well.

IMO the spec will need to settle on some methods and signature suites, because otherwise you get into a situation where all kinds of parties support VCs and OBV3, but they cannot receive or verify VCs/VPs, simply because they do not support the particular DIDs or key types used by the issuer and holder

**Comment by justinpitcher** [comment]
It is unnecessary in my opinion to enforce a specific DID method as it is unnecessary and arguably a burden to platforms.

It's also highly likely we would make a short-sighted selection.

> if different implementations choose different DID methods, there will be no interoperability

Any platform can read any DID using the [universal resolver](https://github.com/decentralized-identity/universal-resolver). Which DID method will be used for authoring new credentials is at the discretion of the issuing platform, but it creates no real barriers to a consuming service.

Certainly I think the ecosystem will organically grow to favour a few select methods, but it would be out of scope for the spec to make normative statements about their use today if ever.

**Comment by nklomp** [comment]
Wait. You are seriously saying that it is okay for parties not knowing how to verify certain DIDs? Reading using a Universal Resolver does not mean you can verify a credential.

If you ask me this will seriously impact adoption. Especially since you will move from a v2 spec, which was an end to end spec that simply means interop as long as you conformed to the spec. You will now move to v3, which means that issuers and verifiers might not be able to verify credentials, because they have different DID methods or serialization formats

**Comment by martyr280** [comment]
+1 Justin, DID method selection at this time is shortsighted as demonstrated in the use of OB3 in the JFF Plugfest by 20+ providers with at a minimum 3 different did methods.  We should not be normative in this regard.


Marty Reed | Chief Executive Officer
RANDA Solutions | 1113 Murfreesboro Rd. | Suite 106 #415 | Franklin, TN 37064
office 615 467 6387 | direct 615 915 5446 | fax 615 613 0517

Confidentiality Disclaimer: This email and any attached files are confidential and intended solely for the use of the individual or entity to which it is addressed. If you are not the person or entity to whom this is addressed, or the person responsible for delivery of this email to the intended recipient, you have received this email in error. Any use, dissemination, distribution, forwarding, printing or copying of this email including attachments is strictly prohibited. If you received this email in error, immediately delete it from your system without copying and notify the sender so that our records can be corrected.
On Nov 17, 2022, at 5:41 AM, Justin Pitcher ***@***.***> wrote:

﻿

It is unnecessary in my opinion to enforce a specific DID method as it is unnecessary and arguably a burden to platforms.

It's also highly likely we would make a short-sighted selection.

if different implementations choose different DID methods, there will be no interoperability

Any platform can read any DID using the universal resolver<https://github.com/decentralized-identity/universal-resolver>. Which DID method will be used for authoring new credentials is at the discretion of the issuing platform, but it creates no real barriers to a consuming service.

Certainly I think the ecosystem will organically grow to favour a few select methods, but it would be out of scope for the spec to make normative statements about their use today if ever.

**Comment by nklomp** [comment]
The only reason it worked, is since we agreed upfront to use these 3 DID methods. Which in turn meant that several implementors had to create a DID:JWK method. We already had foreseen that if we didn't agree, we would never be able to show interop across the cohort.

Also I would refrain from calling things shortsighted. You are talking with people that actually have a bit of experience in the SSI world

**Comment by martyr280** [comment]
Fair, I retract that portion of my statement.

**Comment by ottonomy** [comment]
There's a balance to be struck -- the spec does prescribe many things about what options within VC must be implemented for consistency across implementations, and there were some layers that were not standardized. For instance, the Proof Types are standardized, but the DID methods for issuers and recipients are not. 

This workgroup would be poorly positioned to make definitive recommendations that would stand up for several years, but we should definitely consider what the implementation landscape will be with a strong eye to avoiding the costs that @Sakurann brought up here. The people who suffer when there is no interoperability are the end users themselves, and lack of interoperability when it says on the tin it's supposed to be interoperable is a gut punch to the momentum of our nascent corner of the VC ecosystem. Finding appropriate mechanisms, whether they are plugfests, normative requirements in the spec itself, or other market-led feedback loops, that lead to widespread actual interoperability is going to be really important. 

One other tool we have is the forthcoming implementation guide, which I'm going to start drafting up in the coming days. I've been focused on this interoperability problem in the space for most of the year in my [public](https://docs.google.com/presentation/d/1Il9HWXAImKVxXmCTpk_gzpFFQVQrldIw8x0pB8eRisI/edit) [presentations](https://docs.google.com/presentation/d/1tfex0VCrro_Ph8_gf-dFzdl1E94x1qxJJTOHVCE2FYk/edit#slide=id.g14bf41bcebb_0_171), calling this the "layer cake" challenge that our ecosystem faces. It's a tricky thing to decide what goes in and out of a spec, and what should be in some kind of complementary resource, just like the [DID Spec Registries](https://w3c.github.io/did-spec-registries/#did-methods) doc is separate from the [DID specification](https://www.w3.org/TR/did-core/) itself.

**Comment by nklomp** [comment]
I think ensuring making some non normative suggestions in an implementation guide at least makes sure you get a big mass of implementations opting to support certain methods. The plugfest mainly choose did:key and did:jwk. There was a sporadic did:web and did:ion.

Almost every implementation will support did:key, simply because it is easy to test with non ledger based DIDs. That is why you saw in the Vc api/chapi cohort basically all using did:key with LDP. Did:key and did:web for that matter would probably be pretty poor choices for issuers.

In the OpenId cohort it was mainly did:jwk spread across JWT and LDP, with a bit of did:key. If the adjusted NGI Atlantic profile would not have been  used, sort of requiring DID:jwk, then I am confident we would also mainly have seen did:jwk.

Point is that because the plugfest showed interop doesn't mean you can say that the DID support amongst implementations will sort itself.

The plugfest participants had to show interop for the transport protocol,  so choosing a safe and simple DID method all support mainly for testing purposes is a safe bet.

These did methods can work for subjects, but certainly not for issuers in production settings (no rotation, no history, no standard service endpoints, no proper verification method relationships)

**Comment by martyr280** [comment]
@nklomp do you have a recommendation on which DID methods we should include in the implementation guide beyond did:key ?

**Comment by kayaelle** [comment]
We could reference the DID Rubric:[ https://www.w3.org/TR/did-rubric/]( https://www.w3.org/TR/did-rubric/)

**Comment by longpd** [comment]
The implementation guide can recognize the DID methods that 1EdTech prefers. It can also suggest that using the DID resolver from DIF can be a backup or alternate method to resolve the DID. But it is too early to say what is THE did method that we should use. It is a good thing to revisit when considering v1.x. The VC DM does specify particular cryptographic signatures that are acceptable, but they've been around and used for many years. This underscores the importance to not over specify the DID method now.

**Comment by longpd** [comment]
+1 to @Kayaelle's suggestion for referencing the DID method choice in the context of the implementation guide.

**Comment by xaviaracil** [comment]
The implementation guide already has a section about DID method choice
