### ISSUE TITLE
Candidate Final Spec Unavailable

### ISSUE THREAD

**Issue by kayaelle** [1EdTech/openbadges-specification#495]
[https://imsglobal.github.io/openbadges-specification/ob_v3p0.html](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html) is returning a 404.

**Comment by amiller-ims** [comment]
Try
https://1edtech.github.io/openbadges-specification/ob_v3p0.html

**Comment by xaviaracil** [comment]
@kayaelle The org name in Github has been renamed from IMSGlobal to 1EdTech. This hasn't affected the repositories' URL, since Github does the redirection. However, Github Pages doesn't do that redirection. That's why https://imsglobal.github.io/openbadges-specification/ob_v3p0.html is no longer valid. 

As @amiller-ims said, the new URL is https://1edtech.github.io/openbadges-specification/ob_v3p0.html

Sorry for any incovenience this change might have caused to you.

**Comment by xaviaracil** [comment]
@kayaelle could you check that the new url is ok? Can I close this issue?

Thanks

**Comment by kayaelle** [comment]
It's available. I'll update where I have links to it. Would you consider a redirect: [https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7](https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7) ?

Thanks!

**Comment by xaviaracil** [comment]
I've set up the redirect from the old url to the new one. 

Take into account that this solution is temporary, so in a near future this old url will stop working (one possible point in time to do so is when the spec goes to public).
